// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCscVpKKkvRVEhQuzB3uvHfXnfu4ncmbtI',
    appId: '1:312618444576:web:0f6ce66701fca6f6379945',
    messagingSenderId: '312618444576',
    projectId: 'share-status-5fa14',
    authDomain: 'share-status-5fa14.firebaseapp.com',
    storageBucket: 'share-status-5fa14.firebasestorage.app',
    measurementId: 'G-9NXD3X0YVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwd8a7DrAhOC5kT4kxA3jk3pcNMREluAM',
    appId: '1:312618444576:android:231126c25b7fe220379945',
    messagingSenderId: '312618444576',
    projectId: 'share-status-5fa14',
    storageBucket: 'share-status-5fa14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT4iLC2vITxLf5Sw35QgdJUQOqoBRST-s',
    appId: '1:312618444576:ios:9840726a4067f212379945',
    messagingSenderId: '312618444576',
    projectId: 'share-status-5fa14',
    storageBucket: 'share-status-5fa14.firebasestorage.app',
    iosBundleId: 'seonho.com.sharestatus.shareStatus',
  );
}
